bup: update to version 0.25-rc1-107-g96c6fa2 and drop -Werror to fix the build
  /nix/store/4jfqcb4mzh3vl08zgfh9ir46jii7rcb9-python-2.7.3/include/python2.7/modsupport.h:27:1: error: 'PyArg_ParseTuple' is an unrecognized format function type [-Werror=format=]
   PyAPI_FUNC(int) PyArg_ParseTuple(PyObject *, const char *, ...) Py_FORMAT_PARSETUPLE(PyArg_ParseTuple, 2, 3);
   ^
  cc1: all warnings being treated as errors