pencil: mark as broken
Currently pencil won't start, due to incompatible firefox version:

  $ pencil
  Error: Platform version '47.0.1' is not compatible with
  minVersion >= 36.0

See https://github.com/prikhi/pencil/issues/840.