dico: mark linux only.
Never built successfully.

    Undefined symbols for architecture x86_64:
      "_rpl_strerror", referenced from:
          _default_print_diag in libgrecs.a(diag.o)
          _grecs_symtab_strerror in libgrecs.a(symtab.o)
          _parse_inet in libgrecs.a(sockaddr.o)
    ld: symbol(s) not found for architecture x86_64

/cc ZHF #45961

(cherry picked from commit 709a828e713b028a3dc5e9de9ed1711a405d010b)