rdiff-backup: unbreak 'rdiff-backup-statistics'
By adding needed module to python sys.path. Fixes this:

  $ rdiff-backup-statistics backup-dir
  Traceback (most recent call last):
    File "/home/bfo/.nix-profile/bin/rdiff-backup-statistics", line 24, in
  <module>
      from rdiff_backup import connection, regress, rpath, Globals,
  restore, \
  ImportError: No module named rdiff_backup