flpsed: mark linux only
Doesn't build on darwin and probably other platforms.

    GsWidget.H:26:3: error: 'Atom' does not name a type; did you mean 'tm'?
       Atom atoms[5];
       ^~~~
       tm
    GsWidget.cxx: In member function 'void GsWidget::setProps()':
    GsWidget.cxx:47:2: error: 'atoms' was not declared in this scope
      atoms[0] = XInternAtom(fl_display,"GHOSTVIEW" , false);
      ^~~~~

/cc ZHF #45961

(cherry picked from commit cd78d0cc3ff97924bbc810b025fc0833e2b71916)