ilixi: mark as broken
It's broken since the directfb 1.6.3 -> 1.7.6 update, commit
bb7138e9a983f8393116af192db38ec2954de401 ("directfb: Update to 1.7.6").

  [...]
  building libilixi_graphics_la-Surface.lo
    CXX    libilixi_graphics_la-Surface.lo
  Surface.cpp: In member function 'void ilixi::Surface::setGeometry(int, int, int, int)':
  Surface.cpp:157:44: error: in C++98 'r' must be initialized by constructor, not by '{...}'
       DFBRectangle r = { x, y, width, height };