runLaTeX: Fix dependency detection
Since Nix 1.4, expressions like "${path}/blabla" always evaluate to a
string rather than a path.  However, findLaTeXIncludes depended on the
old (weird) behaviour, leading to errors like:

  error: string `/nix/store/4c32q75in74m1148anlzdhb8jpppab0s-bla/IEEEtran.cls' cannot refer to other paths

So use path concatenation instead.