waf: 2.0.6 -> 2.0.10
This commit also swaps the build tool to use python3 internally (which waf fully
supports and prefers) and swaps the src to be downloaded from gitlab. The waf.io
site only keeps source tarballs of the latest version, so once a new waf comes
out we can no longer reproduce older versions.

We need the ensureNewerSources hook to avoid this error, in both `python2` and `python3`:

    ValueError: ZIP does not support timestamps before 1980