Revert "uchiwa: 0.22.1 -> 0.25.3-1"
This reverts commit 5dc5dfdefb9719b8567c13de691cf2ccdbde95a3.

This breaks evaluation:
error: invalid character ‘/’ in name ‘angular-tools/ng-jsoneditor-ea138469f157d8f2b54ec5b8dcf4b08a55b61459’

cc @peterhoeg