gcc: Disable profiled build
This can fail randomly with an error like:

building toplev.o
../../gcc-4.6.3/gcc/reload.c: In function 'find_reloads':
../../gcc-4.6.3/gcc/reload.c:3778:11: error: corrupted value profile: value profile counter (93791 out of 95865) inconsistent with basic-block count (95759)

http://hydra.nixos.org/build/7185029

On the plus side, this makes building GCC much faster because it
re-enables parallel building.