update to 2.4.6, python import problems are still there:
(gimp:9911): LibGimpBase-WARNING **: gimp: gimp_wire_read(): error
Traceback (most recent call last):
  File "/nix/store/41hi79yr3k46yx98yfanpxbdcdslbgql-gimp-2.4.6/lib/gimp/2.0/plug-ins/happy-valley-relief.py", line 20, in ?
    from gimpfu import *
  File "/nix/store/41hi79yr3k46yx98yfanpxbdcdslbgql-gimp-2.4.6/lib/gimp/2.0/python/gimpfu.py", line 74, in ?
    import gimp
ImportError: could not import pygtk

svn path=/nixpkgs/trunk/; revision=11942