Revert "haskell-gtkglext: update to version 0.12.5.0"
Because it breaks nixpkgs evaluation:

$ nix-env -f . -qa '*' --meta --xml --drv-path --show-trace
error: while querying the derivation named `haskell-gtkglext-ghc7.6.3-0.12.5.0':
while evaluating the attribute `propagatedNativeBuildInputs' of the derivation `haskell-gtkglext-ghc7.6.3-0.12.5.0' at /home/bfo/nixpkgs/pkgs/build-support/cabal/default.nix:70:13:
infinite recursion encountered

This reverts commit 6ba32aa8bdfd73b6b55d07f270a3f344007ab7cb.