whisper: upgrade to the same version as the other graphite components
Without this we get the following Python exception when trying to fetch
a graph in the graphite web app:

    File "/nix/store/nj62jqk2xmp5c3h93pfnlqn66qj1kkvs-python-2.7.12-env/lib/python2.7/site-packages/opt/graphite/webapp/graphite/storage.py", line 335, in fetch
      return whisper.fetch(self.fs_path, startTime, endTime, now)
  TypeError: fetch() takes at most 3 arguments (4 given)

Fixes #21032.

(cherry picked from commit b4005bbac0530c711a7bed56722ba63a0883d9f7)