john: use gcc 4.9 instead of 5 (unbreaks build)
Fixes this build error:

  dynamic_fmt.o: In function `DynamicFunc__crypt_md5_to_input_raw_Overwrite_NoLen':
  .../john-1.8.0-jumbo-1/src/dynamic_fmt.c:4989: undefined reference to `MD5_body_for_thread'

Upstream issue:

  https://github.com/magnumripper/JohnTheRipper/issues/1093

(cherry picked from commit d5656873d7b0d5bc52794b3d2c403835426ebd5e)