Fix nixpkgs eval (caused by 'emscripten' expression)
Fixes this:

 $ nix-env -f . -qa '*' --meta --xml --drv-path --show-trace
 error: while evaluating ‘callPackageWith’ at .../lib/customisation.nix:93:35, called from .../pkgs/top-level/all-packages.nix:1411:24:
 while evaluating ‘makeOverridable’ at .../lib/customisation.nix:54:24, called from .../lib/customisation.nix:97:8:
 undefined variable ‘srcFC’ at .../pkgs/development/compilers/emscripten-fastcomp/default.nix:26:14

Also, "matthewbauer" is not defined in ./lib/maintainers.nix, comment
out.

Caused by f646b9295ea7a2332667f5ffeb5bd871e76982e9 and
d078fe1e9c826a63ad078ca4d5364c967984f393.