kde4.kdepimlibs: fixup build by using older cmake
I have no idea why, but apparently the last cmake update caused:
  kdepimlibs-4.14.3/akonadi/tests/../pastehelper.cpp:343:27:
    fatal error: pastehelper.moc: No such file or directory