coreutils: update to 8.20. They didn't build in i686 here.
Here is the error:
set-mode-acl.c: In function 'qset_acl':
set-mode-acl.c:72:6: error: #error Must have acl_delete_def_file (see POSIX 1003.1e draft 17).