python-namebench: fix error preventing it from starting
namebench expects to be run from its own source tree (it uses relative
paths to various resources), make it work.

The current version fails like this:

  $ ./result/bin/namebench.py
  Traceback (most recent call last):
    File "/nix/store/04d29llycr5xcxplfv4gn556nzm1mrl7-python2.7-namebench-1.0.5/bin/.namebench.py-wrapped", line 46, in <module>
      (options, supplied_ns, global_ns, regional_ns) = config.GetConfiguration()
    File "/nix/store/04d29llycr5xcxplfv4gn556nzm1mrl7-python2.7-namebench-1.0.5/lib/python2.7/site-packages/libnamebench/config.py", line 27, in GetConfiguration
      (configured_options, global_ns, regional_ns) = ProcessConfigurationFile(options)
    File "/nix/store/04d29llycr5xcxplfv4gn556nzm1mrl7-python2.7-namebench-1.0.5/lib/python2.7/site-packages/libnamebench/config.py", line 100, in ProcessConfigurationFile
      general = dict(config.items('general'))
    File "/nix/store/z6vp5aix4ks1zdjdry7v7dahg8dd02sy-python-2.7.10/lib/python2.7/ConfigParser.py", line 642, in items
      raise NoSectionError(section)
  ConfigParser.NoSectionError: No section: 'general'