gradm: fix build on i686
This is a regression introduced by my update at e4b7b7b028e0ce724ea6e4bfad156b78d7ef7b8e

Turns out this was actually required to build the package on i686; without it,
the build fails with

```
/nix/store/[...]-flex-2.6.0/lib/libfl.so: undefined reference to `yylex'
```

for some reason ... the easiest solution is to just use flex_2_5_35, which does
build successfully.