a2jmidid: wrap python path for a2j_control, fixes #6916
a2j_control fails because dbus is not in the python path. The exact error
message is:

    Traceback (most recent call last):
      File ".nix-profile/bin/a2j_control", line 11, in <module>
	import dbus
    ImportError: No module named dbus

The fix is to add the python dbus module to the build inputs and wrap the
python path for a2j_control.