glusterfs: Fix wrong xattr package: xattr -> pyxattr.
Fixes error

  File "/nix/store/lxpsl84km87xpk59nai6a33ihgpfs7qr-glusterfs-3.10.2/libexec/glusterfs/glusterfind/changelog.py", line 105, in populate_pgfid_and_inodegfid
      file_xattrs = xattr.list(p)
  AttributeError: 'module' object has no attribute 'list'

when using `glusterfind pre`.

(cherry picked from commit 8e329da496f8e7f3c5b95c721b7a95317f5854c4)