cargo-web: mark broken on darwin
Looks CoreFoundation related.

    Undefined symbols for architecture x86_64:
      "_CFURLResourceIsReachable", referenced from:
          fsevent_sys::core_foundation::str_path_to_cfstring_ref::h0ea4bd94e2c613f2 in libfsevent_sys-ef30b6879660a6c1.rlib(fsevent_sys-ef30b6879660a6c1.fsevent_sys7-49ce33334334dd3a5c7883bf4070f954.rs.rcgu.o)
    ld: symbol(s) not found for architecture x86_64

/cc ZHF #45961

(cherry picked from commit 327edb4b1dc556b0342bde232c479cdcd0176997)