gencfsm: mark as broken
With staging merged into master, we now have gnome3 = gnome3_22;.

and

error: while querying the derivation named ‘gnome-encfs-manager-1.8.16’:
while evaluating the attribute ‘nativeBuildInputs’ of the derivation
‘gnome-encfs-manager-1.8.16’ at
nixpkgs/pkgs/tools/security/gencfsm/default.nix:6:3:
while evaluating ‘getOutput’ at nixpkgs/lib/attrsets.nix:453:23, called
from undefined position:
attribute ‘libgee_1’ missing, at
nixpkgs/pkgs/tools/security/gencfsm/default.nix:14:27

cc maintainer @spacefrogg