ghc 7.0.2 and 7.0.3 are "broken" because of build errors with recent versions of GCC
  rts/StgCRun.c: In function 'StgRunIsImplementedInAssembler':

  rts/StgCRun.c:208:1:
       error: frame pointer required, but reserved
       StgRunIsImplementedInAssembler(void)
       ^

  In file included from includes/Stg.h:230:0:
      0,
                       from rts/StgCRun.c:70:

  includes/stg/Regs.h:323:20:
       note: for 'Sp'
       GLOBAL_REG_DECL(P_,Sp,REG_Sp)
                          ^

  includes/stg/Regs.h:174:54:
       note: in definition of macro 'GLOBAL_REG_DECL'
       #define GLOBAL_REG_DECL(type,name,reg) register type name REG(reg);
                                                            ^