aften: Disables build on aarch64-linux
It looks like it would be a trivial fix with
`-Wno-shift-negative-value`, but in the end it fails with:

```
[100%] Linking C executable aften
libaften_static.a(a52enc.o): In function `aften_encode_init':
a52enc.c:(.text+0x303c): undefined reference to `apply_simd_restrictions'
collect2: error: ld returned 1 exit status
```

So it looks like it's not simply a warning issue.