Revert "linux: 4.9.35 -> 4.9.36"
This reverts commit c9cf9ceac3b247be874fd1879fb523d8ccff6d87.

Upstream commit b6f75b986a7f7b79953b94f9778de295a253c624 [1] adds a call to a non-existent function, breaking perf:

util/probe-event.c: In function 'post_process_module_probe_trace_events':
util/probe-event.c:669:9: error: implicit declaration of function 'post_process_probe_trace_point' [-Werror=implicit-function-declaration]
   ret = post_process_probe_trace_point(&tevs[i].point,
         ^
util/probe-event.c:669:3: error: nested extern declaration of 'post_process_probe_trace_point' [-Werror=nested-externs]
   ret = post_process_probe_trace_point(&tevs[i].point,
   ^

[1] https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git/commit/tools/perf/util/probe-event.c?h=v4.9.36&id=b6f75b986a7f7b79953b94f9778de295a253c624