Revert "ldb: 1.1.27 -> 1.3.1"
This reverts commit bc474e2dd847776193678ef83143c92da4925d95.

Source hash is incorrect:

https://hydra.nixos.org/build/68234054

And even fixing it doesn't make it compile:

Checking for system tdb (>=1.3.15)                                                : not found
ERROR: System library tdb of version 1.3.15 not found, and bundling disabled
builder for ‘/nix/store/bxnawxa402vrv4qmcmj2hmp98a0bz7li-ldb-1.3.1.drv’ failed with exit code 1
error: build of ‘/nix/store/bxnawxa402vrv4qmcmj2hmp98a0bz7li-ldb-1.3.1.drv’ failed