fox: mark broken on darwin
    Undefined symbols for architecture x86_64:
      "_MPCreateSemaphore", referenced from:
          FX::FXSemaphore::FXSemaphore(int) in FXThread.o
          FX::FXSemaphore::FXSemaphore(int) in FXThread.o
      "_MPDeleteSemaphore", referenced from:
          FX::FXSemaphore::~FXSemaphore() in FXThread.o
          FX::FXSemaphore::~FXSemaphore() in FXThread.o
      "_MPSignalSemaphore", referenced from:
          FX::FXSemaphore::post() in FXThread.o
      "_MPWaitOnSemaphore", referenced from:
          FX::FXSemaphore::wait() in FXThread.o
          FX::FXSemaphore::trywait() in FXThread.o
    ld: symbol(s) not found for architecture x86_64

/cc ZHF #45961

(cherry picked from commit 6390b8b63e623d83558ff97102cd8a21ed99dd75)