Revert "nodePackages.yarn: remove package"
This reverts commit 986dba716f8244304e5e9afb92924eb543fc5596.

Fixes:

    error: anonymous function at /home/travis/build/NixOS/nixpkgs/pkgs/development/node-packages/node-env.nix:3:1 called with unexpected argument ‘python’, at /home/travis/build/NixOS/nixpkgs/pkgs/development/node-packages/composition-v6.nix:8:13

This commit is doing a lot more than removing the yarn package, it also
upgrades a ton of other packages.