libselinux: Make easier to build against Python 3
If we now use something like this:

pkgs.libselinux.override {
  enablePython = true;
  python = pkgs.python3;
}

... we now no longer will get the following error:

selinuxswig_wrap.c:143:21: fatal error: Python.h: No such file or directory

This happens because the Makefile is using the Python interpreter to get
the right library dir for Python:

PYTHONLIBDIR ?= $(shell $(PYTHON) -c "
  from distutils.sysconfig import *;
  print(get_python_lib(1))
")

Signed-off-by: aszlig <aszlig@redmoonstudios.org>