bluez5: add missing dependency on pygobject
Fixes this:

  $ bluez-monitor-bluetooth
  Traceback (most recent call last):
    File "/nix/store/d3gv219wnnjd2c9agyq2gjpwxp0m84l8-bluez-5.8/test/.monitor-bluetooth-wrapped", line 5, in <module>
      import gobject
  ImportError: No module named gobject