readline-6.3: Fix building on Darwin
The zip file contains files named CHANGELOG and ChangeLog, so the
build fails on case-insensitive systems with:

  error: creating file `/nix/store/nix-4888-0/unpacked/ChangeLog': File exists

The official tar distribution does not have this problem.