hydra: don't support Nix 1.x
The component `hydra-evaluator` requires `pool.hh` from Nix which isn't
provided by Nix 1.x and thus fails with the following error in this
case:

```
hydra-evaluator.cc:3:10: fatal error: pool.hh: No such file or directory
 #include "pool.hh"
          ^~~~~~~~~
compilation terminated.
make[3]: *** [Makefile:443: hydra_evaluator-hydra-evaluator.o] Error 1
```

As the commit is from 2016 and fairly hard to revert for Nix 1.x
support, it's easier to drop that.

This has been tested with fixed perl-bindings for Nix1 as done in #55146.