Updated leksah-process and leksah-server to version 0.10.x.
Unfortunately, I cannot test these updates because gtksourceview doesn't
compile:

  ./gtksourceview2.h:10:48: fatal error: gtksourceview/gtksourceundomanager.h: No such file or directory

Not sure what that means.

svn path=/nixpkgs/trunk/; revision=28341