Fix eval
$ nix-env -f . -qa '*' --meta --xml --drv-path --show-trace
error: while querying the derivation named ‘python2.7-rpkg-1.50’:
attribute ‘gpl2plus’ missing, at .../pkgs/development/python-modules/rpkg/default.nix:24:15

Introduced by commit c29a721350add1addf2a8b77d0c591312f817a5a
("rpkg: 1.14 -> 1.50").