attic: unbreak "attic mount" by using old llfuse 0.41
llfuse >= 0.42 has breaking changes, causing "attic mount" to fail:

  TypeError: main() got an unexpected keyword argument 'single'

Side note: borgbackup, a fork of attic, has been updated to work with
newer llfuse.